[tool.poetry]
name = "dji-proxy-timecode-match"
version = "0.1.0"
description = ""
authors = ["yuanyi wu <wuyuanyi135@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
